#! /usr/local/bin/bash

# Summarize the .txt files generated by course_mapper.py

# Command line options: -i to skip (ignored) lines
unset ignore
while [[ $# > 0 ]]
do
  case $1 in

      -i) ignore=ignore
          ;;

       *) echo "Usage: $0 [-i]"
          echo "   -i:  Skip “(ignored)” lines"
          exit 1
          ;;
  esac
  shift
done
(
  cd ~/Projects/course_mapper/reports
  echo -e `date` '\n\nBLOCK COUNTS' > report_summaries.txt

  cat blocks.txt|cut -c 1-3,15-|sort|uniq -c >> report_summaries.txt
  n_top=`ack Top-level blocks.txt|wc -l`
  n_nest=`ack nested blocks.txt|wc -l`
  n_total=`wc -l blocks.txt`
  echo '   ------------------' >> report_summaries.txt
  printf "   %'d %s\n" ${n_top} "Top Level" >> report_summaries.txt
  printf "   %'d %s\n" ${n_nest} "Nested" >> report_summaries.txt
  printf "   %'d %s\n" ${n_total/blocks.txt/} "Total" >> report_summaries.txt

  echo -e "\n`wc -l anomalies.txt|awk '{print $1}'` ACAD PLANS w/ WRONG BLOCK TYPES" >> report_summaries.txt
  cat anomalies.txt >> report_summaries.txt

  for r in log todo fail no_courses
  do
    n=`wc -l ${r}.txt|cut -d ' ' -f 1`
    echo -e "\n" `printf "%'d" $n` "$r" | tr a-z A-Z >> report_summaries.txt
    echo ' -------------------------------------------------------------------------------' \
         >> report_summaries.txt
    if [[ $r = no_courses ]]
    then
        cat ${r}.txt|sort|uniq -c|sort -r >> report_summaries.txt
    else
      if [[ $ignore ]]
      then
        cut -c 16- ${r}.txt|ack -v '(ignored)'|sort|uniq -c|sort -r >> report_summaries.txt
      else
        cut -c 16- ${r}.txt|sort|uniq -c|sort -r >> report_summaries.txt
      fi
    fi
  done

  # Subplans and Others
  echo -e "\n Subplan References" >> report_summaries.txt
  echo ' -------------------------------------------------------------------------------' \
       >> report_summaries.txt
  ack 'Subplan' subplans.txt | sort|uniq >> report_summaries.txt

  echo -e "\n Other Block References" >> report_summaries.txt
  echo ' -------------------------------------------------------------------------------' \
       >> report_summaries.txt
  ack 'Other' subplans.txt |cut -c 16- | sort|uniq -c| sort -r >> report_summaries.txt

  echo -e "\n`wc -l activeplans_missing.txt|awk '{print $1}'` MISSING SCRIBE BLOCKS" >> report_summaries.txt
  cat activeplans_missing.txt >> report_summaries.txt
)

