#! /usr/local/bin/python3
""" Create a spellcheck report of labels.
    Using the labels.txt file generated by the mapper and the edited_labels.txt file generated by
    running aspell. prepare a report of recommended label changes.
"""

import csv
import sys

from pathlib import Path
